    FROM alpine:3.9
    WORKDIR /space-cloud
    RUN set -ex  \
      && apk add --no-cache ca-certificates unzip libc6-compat sed

    RUN wget https://spaceuptech.com/downloads/linux/space-cloud.zip -O space-cloud.zip

    COPY space-cloud.sh .
    RUN unzip space-cloud.zip \
        && rm space-cloud.zip \
        && chmod +x space-cloud \
        && chmod +x space-cloud.sh

    COPY config.yaml .

    ENV PROD=false
    ENV PATH="/space-cloud:${PATH}"

    EXPOSE 8080
    CMD ./space-cloud.sh
    #CMD sleep 900